language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - bunnyppl@hotmail.com
    on_success: always
    on_failure: always

branches:
  only:
   - master

before_script:
  - npm install -g @angular/cli
  
script:
  - ng build --prod --base-href https://kenken64.github.io/csf_assessment1/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/assessment1
  on:
    branch: master
